### ISSUE TITLE
Parsing OBJECT IDENTIFIER (OID)

### ISSUE THREAD

**Issue by gaetanww** [KizzyCode/asn1_der-rust#4]
Is it possible to parse OIDs using that library?

**Comment by KizzyCode** [comment]
Not directly. You can always extract them as generic [`DerObject`](https://docs.rs/asn1_der/0.6.2/asn1_der/struct.DerObject.html) and parse then manually, but there is no specific parser yet; sry 😕
If you write some, feel free to commit 😊

**Comment by KizzyCode** [comment]
Sorry, but I decided to limit this crate to basic and native-representable types only 😊
