### ISSUE TITLE
Installation and usage?

### ISSUE THREAD

**Issue by tbmreza** [KizzyCode/asn1_der-rust#5]
- As a novice both in ASN.1 encoding and Rust, I'd appreciate a dedicated section for installation/usage guide.

- I found this project through github search. The README only makes sense if read from crates.io, where the github repo is linked at the top. Maybe put this link at the README forefront or the repo About? https://crates.io/crates/asn1_der

**Comment by KizzyCode** [comment]
Well on your first point: There's always the documentation at [![docs.rs](https://docs.rs/asn1_der/badge.svg)](https://docs.rs/asn1_der), which includes an example as well as the entire API documentation.

To include the crate into your project, go to your projects `Cargo.toml` and insert `asn1_der = "0.7.1"` into the `[dependencies]`-section (see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html for more details).
However, including Cargo-dependencies is basic Rust knowledge and IMHO a little bit out of scope for a readme (no offense 😊).

On your second point, I already have the standard [![crates.io](https://img.shields.io/crates/v/asn1_der.svg)](https://crates.io/crates/asn1_der)-badge directly on top of the readme which links to https://crates.io/crates/asn1_der. Or am I misunderstanding your point here?

Please feel free to ask if you have further questions or suggestions 😊

**Comment by tbmreza** [comment]
That makes sense to me! I am not used to checking the badges, I always thought they are decoration.
Please feel free to close this issue. I am sorry that you had to take the time to explain.

**Comment by KizzyCode** [comment]
No worries; please feel free to ask again if you have further questions 😊
