### ISSUE TITLE
LICENSE BSD 2-CLAUSE contained in this repository is divergent

### ISSUE THREAD

**Issue by joao-paulo-parity** [KizzyCode/asn1_der-rust#6]
The current version on master (https://github.com/KizzyCode/asn1_der-rust/blob/60743ebaebdb621c47ad254b0e5987a9ba8cafde/LICENSE%20BSD%202-CLAUSE.md) appears to diverge in the wording from the online texts I have found of that license.

https://opensource.org/licenses/BSD-2-Clause

https://spdx.org/licenses/BSD-2-Clause.html

In both of the above online sources, in the part where it says:

`THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT`

The version in this repository says `COPYRIGHT OWNER` instead of `COPYRIGHT HOLDER`.

---

I only caught this divergence through a tool I am developing for the legal team at my company. Please bear in mind that I don't have licensing knowledge nor can say if the texts are equivalent, however I do think the license should not be branded as "BSD-2-Clause" if the text is anyhow different from the official one.

**Comment by KizzyCode** [comment]
That's a nice catch! Honestly I'm quite puzzled where the "OWNER" comes from, because I'm pretty certain I simply copy-pasted the text... 😅
Guess I'll have to update a few repos 🙈

Thank you!
